### PR TITLE
[WIP] Import command for django-blog-zinnia

### PR DESCRIPTION
**Pull request by benjaoming**
This might be pending a bit of extra refinements. But I've already done a successful import of 106 blog posts.

### CODE REVIEW

**Comment by benjaoming** [comment]
I'm not considering adding tests, since it would require django-blog-zinnia in test requirements.. which may now or in the future conflict with requirements of wagtail_blog, for instance for the taggit library.

**Comment by benjaoming** [comment]
Garh, the breakage seems to be caused by this, see thread "[Distutils] latest setuptools appears to require six in a breaking way"

https://mail.python.org/pipermail/distutils-sig/2017-January/thread.html#30057

**Comment by bufke** [comment]
What if you made a new repo for the import command, tested it with django-blog-zinnia, and I just put a note on the readme about it here? This code doesn't really need to be part of core wagtail_blog right?

**Comment by benjaoming** [comment]
@bufke true, let's just do that

**Comment by bufke** [comment]
Cool just send a merge request or let me know if you want a comment about it in the readme

**Comment by benjaoming** [comment]
I'll probably just do a Gist, since I don't have time to setup the whole PyPi+tests+Travis machine for an app that I most likely won't wanna maintain after I'm done importing my own stuff :) Sorry about trying to dump code in your project, for a moment I just thought it was fine :)

**Pull request closed without merging**
