### PR TITLE
[WIP] Respect custom image model setting WAGTAILIMAGES_IMAGE_MODEL

### PR DESCRIPTION
**Pull request by benjaoming**
In case of bootstrapping wagtail_blog with a custom image model, this would make life a bit easier...

I'm still riding the hard-copied codebase train though :)

### CODE REVIEW

**Comment by benjaoming** [comment]
Am writing down documentation for introducing a custom image model in the middle of a Wagtail project.. Will just give a final thumbs up, when I know that this is the way to go.

**Comment by benjaoming** [comment]
Ah yes okay the Travis configuration is gone.

**Comment by bufke** [comment]
Ok - let me know.

**Comment by benjaoming** [comment]
I removed the migration changes, but because this is a reusable application, it's a bit complicated. It should of course respect `WAGTAILIMAGES_IMAGE_MODEL`, but the migrations should not be made dynamic:

1. If you bootstrap a project without `WAGTAILIMAGES_IMAGE_MODEL` set, but you later change it, then the migration system can only detect this because the previous migrations had a hard-coded value.

1. If you bootstrap a project with `WAGTAILIMAGES_IMAGE_MODEL` already defined, then this will be used in `blog/models.py`, but the migrations will not match. Therefore, a migration will be detected in this case. Creating the migration and applying it would alter the new database layout to match the models. So this would be safe too -- except for the part where the user is creating migrations in a reusable app, that's not common practice.

**Comment by benjaoming** [comment]
Oh, let me just add: I removed the migration changes, because it would render Django unable to detect changes to `WAGTAILIMAGES_IMAGE_MODEL`. I don't think anyone is better off with an assumption that they always define `WAGTAILIMAGES_IMAGE_MODEL` before enabling `wagtail_blog`, they might as well have a big project that has the default model, and when they enable `wagtail_blog`, they find out that they want a custom image model as well... or that's what I did :)

**Comment by benjaoming** [comment]
If anyone says anything about this subject, you can refer them to this discussion that I had with myself :)

**Comment by bufke** [comment]
Note if you resubmit this on [gitlab](https://gitlab.com/thelabnyc/wagtail_blog/merge_requests) you'll get nice CI checks right in the MR.

**Comment by benjaoming** [comment]
That's nice, I guess just as nice as what was working fine before you spend time migrating the repo? :smile: 

I can't do this right now, not feeling the motivation, but please do what you want with this PR/MR.

**Comment by benjaoming** [comment]
Not sure where this is headed, opened up a Django 2.0 support PR that contains this.

**Comment by benjaoming** [comment]
See  #53

**Pull request closed without merging**
