### PR TITLE
XML import fixes

### PR DESCRIPTION
**Pull request by benjaoming**
Issues encountered when importing Wordpress XML, thinking they look harmless... unless `record = ""` has a special meaning, which I don't think it does, and that case would break anytime.

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for a great project btw!

**Comment by benjaoming** [comment]
Sorry that this became a rather messy PR, I'm done now :)

I hope the addition of skipping attachments in XML imports is welcome, I really have no use for these types of blog posts. I think 99% of Wordpress users would never put preservation-worthy content in the descriptions of their Attachments.

**Comment by benjaoming** [comment]
Went a little fast yesterday, now there's tests.

I probably won't work much more on this, as my import looks satisfactory now :)

Thanks again!

**Comment by benjaoming** [comment]
NB! Added Django 1.10 support for the demo app.

**Comment by bufke** [comment]
Thanks. I've found importing from wordpress to be very case by case. In the future, please open a new pull request for features like Django 1.10 support so that I can merge them in one at a time (lots easier to review and merge the django patch as opposed to the xml changes). Thanks again.

**Comment by benjaoming** [comment]
Hi @bufke - thanks for merging it and sorry about the review troubles - I was working in a Django 1.10 environment, had a bit of a tight schedule and wasn't able to test it properly without the demo app, will try to keep PRs slim, but this was - as you say - the import is a lot of "oh okay" realizations with this XML stuff :)

**Pull request merged**
