### PR TITLE
[Used to be WIP, now it's RIP] Swappable models

### PR DESCRIPTION
**Pull request by benjaoming**
Since the approach in #42 wasn't working, I started work on using swappable models instead.

I can't say that it's finished. I need to work through the following:

 - [x] Write a guide on how to start a fresh application with custom models
 - [x] Make `content_panels` property on swappable models only set when NOT swapped out
 - [ ] Make upstream PR to patch Django's fault when m2m `through=` model swapped out
 - [ ] Add a monkey patch in PR to make the case more compelling.
 - [ ] State whether it's possible to migrate an existing project (i.e. change the swappable model)
 - [x] Completely remove `default_author` from migration 0005 or make it conditional.

### CODE REVIEW

**Comment by benjaoming** [comment]
Faulty analysis - don't read
=====================

The following is stupid and misinformed, I wrote it while playing around with swapping in ALTERED models.

The only way to work with swappable models is to start by swapping in IDENTICAL models, applying changes only after running `migrate blog`.

Problem
-----------

~I found that adding custom models through swappable interface creates a circular dependency in the migrations of `blog` and `myapp`.~

 * ~`blog`: Needs `Migration.dependecies` to list for instance `swapper.dependency('blog', 'BlogPage')`~
 * ~`myapp` Needs to generate new migrations with new models. As soon as the models are created in `myapp.models` and one runs `makemigrations myapp`, the circularity will show up because the migrations in `blog` are now looking for `myapp.BlogPage` etc. in the migration model tree.~

Solution
-----------

~It's easy to solve by creating empty models for every swapped in model, so in `myapp.models`, we put all the desired swapped in models and run migrations. AFTER that, we change their model bases and update the swappable settings of the project.~

~So, essentially, we get 2 steps for swapping in new models:~

1. ~Create empty models in `myapp.models` with no model base for each of the swappable models in `blog`.~
1. ~Run `makemigrations myapp`~
1. ~Change the model bases for the models and update your `project.settings`, pointing the swappable model settings to `myapp.BlogPage` etc.~
1. ~Run `makemigrations myapp` again to update the models in `myapp.models`~

~We need, however, to add empty models for ALL of the swappable `blog` models, otherwise foreign keys fail.~

```python
class BlogIndex(models.Model):
    pass

  
class BlogPage(models.Model):
    pass
 
 
class BlogCategory(models.Model):
    pass
 
 
class BlogTag(models.Model):
    pass
 
class BlogPageTag(models.Model):
    pass
 
 
class BlogCategoryBlogPage(models.Model):
    pass
```

Left for investigation
------------------------

~At the moment, I'm unsure about:~

* ~...if some of the swappable models can be left out or not, i.e. if it's all or nothing.~
* ~...if you HAVE to run `migrate blog zero` before applying the migrations for the new swappable models, I found in Postgres that some odd constratins were left behind on the `BlogPageTag` model, pointing to `blog_blogpage` rather than `myapp_blogpage`~

**Comment by benjaoming** [comment]
Just had the first indication that this can be made to work, however:

1) Need to patch Django because `through` models for many-to-many relationships are not swappable, so this fails:
    
       through=swapper.get_model_name('blog', 'BlogCategoryBlogPage')
    
    I managed to make Django eat it, but I don't know enough about the subject to actually make this work, so my suggestion for upstream is going to be to remove a certain check on custom m2m models.

2) `content_panels` in Wagtail do not work for swapped out models. So for instance, if we specify these panels on `blog.models.BlogPage` (for default usage), we have to remove it to make way for the swappable part (or disable it through a setting)

What I'm saying is that this can be achieved, but it's not easy :)

**Comment by benjaoming** [comment]
This PR is still active, I just have issues finding the time to finish the alleged `m2m` Django bug and running the whole procedure with a fresh project.

**Comment by bufke** [comment]
Moved https://gitlab.com/thelabnyc/wagtail_blog/merge_requests/46

**Comment by benjaoming** [comment]
@bufke funny, I was actually working on this yesterday -- if I push something to my Github branch, will it reflect on Gitlab?

**Comment by bufke** [comment]
Gitlab is preferred but I'll merge whatever you send if it works. I was actually just talking about this with a coworker. We decided to just extend the model instead of replacing it for a project.

**Comment by bufke** [comment]
Would love to know if you have any updates on the m2m issue you found. It's concerning if we have to turn to hacks to get the models to be swappable.

**Comment by benjaoming** [comment]
@bufke I'm currently re-implementing this for its original purpose... I got really derailed with this effort, so my mental model of the original M2M is completely eradicated :) Finish what you start, Ben!!

Oddly, what I have right now is working, I just need to figure out why and if I hacked/monkey-patched something or not...

Regarding work on Github... you don't have a CI active anymore? I retained the `.travis.yml` in this PR, but I don't know if that'll work... I'll squash and rebase everything in any case, so can remove it again if it doesn't work out.

**Comment by benjaoming** [comment]
@bufke aha! nevermind, I get "pipeline has failed" notifications from Gitlab now, will investigate! :)

**Comment by benjaoming** [comment]
# Don't use swappable models for this

I have completed my investigation, and I will not pour anymore time into this. I conclude that it will never be efficient for reusable third-party app of the relatively small size of wagtail_blog to instruct users to use swappable models.

For my own purposes, I will now just proceed to hard-copying the whole app into my project.

It's too complicated to achieve swappable models: The docs and the support following it will just break the development of the app itself. From my own experience of maintaining apps, I would say that it's guaranteed that adding this as an option would spawn so many support issues that actually developing new features would be totally derailed. Not to mention maintaining support of the swappability itself.

The way to achieve this would have been:

1) Create an app with a set of models, each must just inherit from the abstract base classes defined in this PR. Add the settings for swappable models.

2) Copy in boiler plate migrations. Django cannot create those with `makemigrations` as it will end up in some circular dependency issue. I had to manually author the migrations to make it work.

3) Start to customize things.

The step with the manually created `0001_initial` killed this for me. I will not want to maintain this for the future of this application.

# What to do then?

The issue here is that we would all like to have reusable blogging features for Wagtail. I would suggest that `wagtail_blog` does NOT at all ship concrete models for any Wagtail-related models. Only abstract models.

Let the user of wagtail-blog implement everything that's supposed to be displayed in Wagtail.

This means that all the views etc. should stop relying on concrete models and instead have either new non-Page models for this data, or that some configurable factory method is defined to return Model classes for what the user should define.

The (re)usefulness of a Wagtail-based blog application is to have models that can be customized.

That is all. Unfortunately the closing of the Github repo has removed other discussions in #28, so I cannot dig out what has previously been mentioned about this topic.

*) user is understood as the developer implementing wagtail-blog for their needs

**Comment by bufke** [comment]
It's all here https://gitlab.com/thelabnyc/wagtail_blog/issues/28

What do you think of this. We add docs that expand on "Feel free to use as is or copy it as a starting point." to be more clear that you might literally want to copy and paste the models. Or note that if the dev finds it acceptable, they just extend the non abstract models.

If this project adds more headache trying to keep it as a installed app while changing it than it solves - why do it. There isn't much to this project. The import scripts would tend to be a one off thing - you don't need them in your app forever. And the only changes I really make here are things to keep up to date on wagtail/django versions.

**Comment by benjaoming** [comment]
I agree @bufke - I think NO DOUBT that the codebase here is valuable, but it is not nice to have started out by using it as a dependency, because 10 minutes later, I find myself scratching my head about "so eh how do I add a field"... which is a very very difficult question at this point :)

You probably have a better perception about how the general usage of this is. But knowing what I know now, then I would definitely start out by cloning the code base.

However, for a longer term, it would be interesting to work on a solution where a dependency and an upgrade path with new features was possible.

**Comment by benjaoming** [comment]
(sorry about these rather quickly/sloppily authored sentences, I hope you can make out what I'm trying to say)

**Pull request closed without merging**
